config/routes.rb
KickAss::Application.routes.draw do
  resources :asses

  root :to => 'asses#index'

end

app/models/ass.rb
class Ass < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/asses_controller.rb
class AssesController < ApplicationController
  # GET /asses
  # GET /asses.json
  def index
    @asses = Ass.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @asses }
    end
  end

  # GET /asses/1
  # GET /asses/1.json
  def show
    @ass = Ass.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ass }
    end
  end

  # GET /asses/new
  # GET /asses/new.json
  def new
    @ass = Ass.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ass }
    end
  end

  # GET /asses/1/edit
  def edit
    @ass = Ass.find(params[:id])
  end

  # POST /asses
  # POST /asses.json
  def create
    @ass = Ass.new(params[:ass])

    respond_to do |format|
      if @ass.save
        format.html { redirect_to @ass, notice: 'Ass was successfully created.' }
        format.json { render json: @ass, status: :created, location: @ass }
      else
        format.html { render action: "new" }
        format.json { render json: @ass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /asses/1
  # PUT /asses/1.json
  def update
    @ass = Ass.find(params[:id])

    respond_to do |format|
      if @ass.update_attributes(params[:ass])
        format.html { redirect_to @ass, notice: 'Ass was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @ass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asses/1
  # DELETE /asses/1.json
  def destroy
    @ass = Ass.find(params[:id])
    @ass.destroy

    respond_to do |format|
      format.html { redirect_to asses_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asses_helper.rb
module AssesHelper
end

app/views/asses/_form.html.erb
<div class="clearfix">
   <%= f.label :name, t("activerecord.attributes.ass.name", :default => "Name"), :class => :label %>
  <div class="input">
    <%= f.text_field :name, :class => 'text_field' %>
  </div>
</div>
<div class="form-actions">
  <button class="btn primary" type="submit">Save</button> or
	<%= link_to "Cancel", asses_path %>
</div>

app/views/asses/edit.html.erb
<%= form_for @ass, :url => ass_path(@ass), :html => { :class => "edit_ass", :id => "edit_ass" } do |f| -%>
  <input name="_method" type="hidden" value="put" />
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/asses/index.html.erb
<h1>Asss</h1>
<table class="table table-striped">
 <thead>
  <tr>
    <th>ID</th>
        <th>
      <%= t("activerecord.attributes.ass.name", :default => t("activerecord.labels.name", :default => "Name")) %>
    </th>
        <th>Created at</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @asses.each do |ass| -%>
   <tr>
    <td><%= ass.id %></td>
        <td><%= link_to ass.name, ass_path(ass) %>
    </td>
        <td><%= ass.created_at %></td>
    <td>
      <%= link_to "Show", ass_path(ass) %>
      <%= link_to "Edit", edit_ass_path(ass) %>
      <%= link_to "Destroy", ass_path(ass), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
    </td>
    </tr>
    <% end -%>
   </tbody>
</table>

<%= link_to "New", new_ass_path, :class => 'btn btn-primary' %>

app/views/asses/new.html.erb
<%= form_for @ass, :url => asses_path, :html => { :class => :form } do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/asses/show.html.erb
<label class="label"><%= t("activerecord.attributes.ass.name", :default => t("activerecord.labels.name", :default => "Name")) %>:</label>
<p><%= @ass.name %></p>

<div class="form-actions">
<%= link_to "Back", asses_path, :class => 'btn'  %>
<%= link_to "Edit", edit_ass_path(@ass), :class => 'btn' %>
<%= link_to "Delete", ass_path(@ass), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KickAss</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>